#################################################
## mysql serverId , v1.0.26+ will autoGen
canal.instance.mysql.slaveId=0

# position info
canal.instance.master.address=host.docker.internal:3306
canal.instance.master.journal.name=
canal.instance.master.position=
canal.instance.master.timestamp=
canal.instance.master.gtid=

# username/password
canal.instance.dbUsername=canal
canal.instance.dbPassword=canal
canal.instance.connectionCharset=UTF-8
canal.instance.defaultDatabaseName=buzzfeed

# table filter regex
canal.instance.filter.regex=buzzfeed\\.item_info
canal.instance.filter.black.regex=mysql\\.slave.*

# mq config
canal.mq.topic=content-change
# 按 creator_id 分区，保证同一创作者的消息有序
canal.mq.dynamicTopic=.*\\..*
canal.mq.partition=0
canal.mq.partitionsNum=3
canal.mq.partitionHash=item_info:creator_id